export const SIDEBAR_ANIMATION_DURATION = 300;
export const HEADER_ANIMATION_DURATION = SIDEBAR_ANIMATION_DURATION / 1000;
export const SIDEBAR_BUTTON_ANIMATION_DURATION = 200;
export const HEADER_ANIMATION_DELAY = SIDEBAR_BUTTON_ANIMATION_DURATION / 1000;