name: Build and Deploy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install -g @bubblewrap/cli

      - name: Generate APK
        run: |
          bubblewrap init --manifest=https://oatnote.io/manifest.json
          bubblewrap build

      - name: Upload APK to Google Play
        env:
          JSON_KEY_FILE: ${{ secrets.PLAY_STORE_JSON }}
        run: |
          echo "${{ secrets.PLAY_STORE_JSON }}" > play-store-key.json
          fastlane supply --json_key_file play-store-key.json --apk ./app-release.apk --track production
